//@ts-nocheck
import type { Metadata } from 'next';
import '../../styles/index.scss';
import Header from '@/components/header/header';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function HomeLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            <main>{children}</main>
            {modal}
        </>
    );
}
